### ISSUE TITLE
Server Tick Loop upon World Creation

### ISSUE THREAD

**Issue by Afrocntrik** [malcolmriley/minecraft-textiles#26] opened 2021-08-19 17:42 UTC
[crash-2021-08-19_13.16.20-server.txt](https://github.com/malcolmriley/minecraft-textiles/files/7016660/crash-2021-08-19_13.16.20-server.txt)

**Comment by malcolmriley** [comment] 2021-08-19 18:04
Hello,

Thank you for the report. Unfortunately I am away from my workspace at the moment, but I will be happy to look into this once I return.

In the meantime, disabling the villager trading feature in the config should prevent more crashes.

Hope your day has otherwise been pleasant.

**Comment by malcolmriley** [comment] 2021-08-21 23:56
Hello again,

I've investigated this issue and after experimenting under various circumstances I have been unable to replicate it with only the Wily Textiles mod installed. I did, however, find a (probably) unrelated bug and have provided a fix in version 0.1.2.

While I believe the cause of your crash to be some kind of mod conflict, please test again with the new version once it is available from CurseForge and advise me of the result.

In the likely case that the new version does not resolve your issue, I would appreciate any other information you have to share about the crash (frequency, possible suspects, etc.) as your mod list is quite long and it will otherwise be quite the undertaking to work through it myself.

**Comment by malcolmriley** [comment] 2021-08-28 06:57
Closing this issue for now, under the assumption that no news is good news. If the issue recurs, feel free to reply here again or open another issue.

**Closed by malcolmriley** 2021-08-28 06:57 UTC
Labels: Bug
